"""Independently-authored adversarial fixtures. Per EXECUTION_PLAN.md §3 (R2, P0).

These fixtures are written separately from the main generation pipeline,
specifically to demonstrate that mechanical_validator.py's checks (schema
validity, source-span binding, execution correctness) do NOT establish
semantic fidelity (property 4). Each fixture has:
  - input: the source text and a generated (possibly wrong) contract.
  - naive_validator_verdict: what mechanical_validator.py actually says.
  - correct_answer: what a semantically-aware check must conclude.

A fixture set generated by the same pipeline it's meant to stress-test would
not serve this purpose -- these are hand-written, not sampled from the
synthetic generation pipeline being validated.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Callable, Dict, List, Optional

from validators.mechanical_validator import (
    ValidationResult,
    check_source_span_binding,
)
from schemas.common import EvidenceSpan


@dataclass
class AdversarialFixture:
    fixture_id: str
    category: str  # negation | omitted_constraint | units_mismatch | conflicting_facts | missing_field
    description: str
    source_text: str
    generated_spans: List[EvidenceSpan]
    naive_check_passes: bool  # what a naive substring/schema check says
    is_actually_correct: bool  # ground truth, established by the fixture author, not by any automated check
    notes: str


def _fixture_negation() -> AdversarialFixture:
    """The exact false-positive example from EXECUTION_PLAN.md §3: citing the
    substring "cotton" as evidence for a "material is cotton" claim, when the
    source text actually says the product does NOT contain cotton."""
    source = "This jacket contains no cotton; shell is 100% recycled polyester."
    span_text = "cotton"
    start = source.index(span_text)
    span = EvidenceSpan(start=start, end=start + len(span_text), text=span_text)
    return AdversarialFixture(
        fixture_id="negation-001",
        category="negation",
        description=(
            "Generated contract claims material=cotton, citing the substring "
            "'cotton' from source text 'contains no cotton'. Substring is "
            "present and correctly bound (naive check passes) but the claim "
            "is the exact opposite of what the source states."
        ),
        source_text=source,
        generated_spans=[span],
        naive_check_passes=True,
        is_actually_correct=False,
        notes="Span-binding alone cannot detect negation scope. Requires an explicit negation-aware check.",
    )


def _fixture_omitted_constraint() -> AdversarialFixture:
    """The exact under-specification example from EXECUTION_PLAN.md §3:
    'nuts without added sugar' -- a generated contract could keep only the
    nuts constraint and silently drop the sugar constraint. The simulator
    can execute the (incomplete) contract just fine."""
    source = "unsweetened oat drink 1 litre without peanuts, no added sugar"
    span_text = "without peanuts"
    start = source.index(span_text)
    span = EvidenceSpan(start=start, end=start + len(span_text), text=span_text)
    return AdversarialFixture(
        fixture_id="omitted-constraint-001",
        category="omitted_constraint",
        description=(
            "Source has THREE explicit requirements (unsweetened/no added "
            "sugar, 1 litre, no peanuts). A generated contract that only "
            "captures the peanut constraint is schema-valid and its one "
            "cited span is correctly bound, but it silently dropped two "
            "critical requirements."
        ),
        source_text=source,
        generated_spans=[span],  # only 1 of 3 required constraints represented
        naive_check_passes=True,
        is_actually_correct=False,
        notes="Neither schema validity nor span-binding can detect an ABSENT constraint -- there's nothing to check against, since the model never emitted it. Requires a completeness check against a pre-specified structured scenario (§3's 'structured-scenario-first' pipeline requirement).",
    )


def _fixture_units_mismatch() -> AdversarialFixture:
    source = "2 x 500ml bottles, total 1 litre"
    span_text = "1 litre"
    start = source.index(span_text)
    span = EvidenceSpan(start=start, end=start + len(span_text), text=span_text)
    return AdversarialFixture(
        fixture_id="units-mismatch-001",
        category="units_mismatch",
        description=(
            "Generated contract claims 'single 1-litre container', citing "
            "the substring '1 litre' from a source describing 2x500ml "
            "bottles. The span is bound correctly (the text '1 litre' does "
            "appear), but the claimed product configuration (one container) "
            "contradicts the actual configuration (two containers)."
        ),
        source_text=source,
        generated_spans=[span],
        naive_check_passes=True,
        is_actually_correct=False,
        notes="plans/02_catalog_and_taxonomy.md is explicit about this exact case: count=2/per_unit=500ml/total=1000ml is not interchangeable with one 1-litre container.",
    )


def _fixture_conflicting_facts() -> AdversarialFixture:
    source = "Waterproof rating: not tested. Marketing copy: fully waterproof for all weather."
    span_text = "fully waterproof"
    start = source.index(span_text)
    span = EvidenceSpan(start=start, end=start + len(span_text), text=span_text)
    return AdversarialFixture(
        fixture_id="conflicting-facts-001",
        category="conflicting_facts",
        description=(
            "Source contains two conflicting statements (an untested rating "
            "field vs. marketing copy). A generated contract that cites only "
            "the marketing copy span is span-bound correctly but ignores a "
            "more authoritative, conflicting field."
        ),
        source_text=source,
        generated_spans=[span],
        naive_check_passes=True,
        is_actually_correct=False,
        notes="plans/01_query_intent_and_constraints.md: 'do not assert electrical/waterproof compatibility from connector shape/marketing alone'. Requires field-authority ranking, not just span presence.",
    )


def _fixture_missing_field_not_negative() -> AdversarialFixture:
    """The inverse failure mode: a validator that's too strict. Absence of
    evidence must map to `unknown`, not `fail` -- plans/00_shared_core.md:
    'a missing field is not a negative factual label'."""
    source = "Wireless mouse, 2.4GHz, USB receiver included."
    return AdversarialFixture(
        fixture_id="missing-field-001",
        category="missing_field",
        description=(
            "Query requires 'Bluetooth compatible'. Source text says nothing "
            "about Bluetooth at all (it describes a 2.4GHz USB-receiver "
            "mouse, which is a different, non-Bluetooth technology). The "
            "CORRECT contract state for the Bluetooth requirement is "
            "'unknown' (no evidence either way) -- NOT 'fail' (which would "
            "require an explicit contradiction) and NOT 'pass' (no positive "
            "evidence exists)."
        ),
        source_text=source,
        generated_spans=[],  # no evidence to cite -- that's the point
        naive_check_passes=True,  # trivially "passes" schema validity with zero spans
        is_actually_correct=True,  # IS correct IF the contract states 'unknown', wrong if it states 'fail' or 'pass'
        notes="This fixture is about the correct handling of absence-of-evidence, not a false positive like the others. A validator must not conflate 'no evidence found' with either 'confirmed false' or 'confirmed true'.",
    )


ALL_FIXTURES: List[AdversarialFixture] = [
    _fixture_negation(),
    _fixture_omitted_constraint(),
    _fixture_units_mismatch(),
    _fixture_conflicting_facts(),
    _fixture_missing_field_not_negative(),
]


def run_naive_check(fixture: AdversarialFixture) -> bool:
    """Runs ONLY the mechanical span-binding check (property 2) against a
    fixture and reports whether it passes -- this is what a naive validator
    relying solely on substring-presence would conclude."""
    if not fixture.generated_spans:
        return True  # vacuously "passes" -- nothing to check
    all_bound, _ = check_source_span_binding(fixture.generated_spans, fixture.source_text)
    return all_bound


def report() -> None:
    """Run every fixture through the naive check and report whether the
    naive check's verdict matches ground truth -- this demonstrates,
    concretely and honestly, which failure modes the current mechanical
    validator catches and which it does not."""
    print(f"{'fixture_id':<28} {'category':<22} {'naive_says_ok':<15} {'ground_truth_ok':<17} {'gap?'}")
    print("-" * 100)
    n_gaps = 0
    for fx in ALL_FIXTURES:
        naive_result = run_naive_check(fx)
        expected_naive = fx.naive_check_passes
        assert naive_result == expected_naive, (
            f"Fixture {fx.fixture_id}: expected naive check to say "
            f"{expected_naive}, but mechanical_validator actually said {naive_result}. "
            f"Fixture authoring bug -- fix the fixture's generated_spans/naive_check_passes."
        )
        gap = (naive_result != fx.is_actually_correct)
        if gap:
            n_gaps += 1
        print(
            f"{fx.fixture_id:<28} {fx.category:<22} {str(naive_result):<15} "
            f"{str(fx.is_actually_correct):<17} {'YES -- naive check insufficient' if gap else 'no gap'}"
        )
    print("-" * 100)
    print(
        f"{n_gaps}/{len(ALL_FIXTURES)} fixtures demonstrate a real gap between the naive "
        f"mechanical check and semantic ground truth. This is EXPECTED and is the "
        f"entire point of §3's four-property distinction -- these gaps are why "
        f"property 4 (semantic fidelity) cannot be certified by mechanical_validator.py "
        f"alone, and why grocery/synthetic data must be reported as synthetic-scenario "
        f"performance rather than assumed semantically correct."
    )


if __name__ == "__main__":
    report()
    print("\nALL validators/adversarial_fixtures.py SMOKE CHECKS PASSED "
          "(fixtures are internally consistent; the naive-vs-ground-truth gap is demonstrated, not hidden)")
